insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (1, 1, 'Island Oasis - Sweet And Sour Mix', 'Often', 43, 105, 17, '11/25/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (2, 2, 'Wine - Magnotta - Red, Baco', 'Weekly', 37, 24, 80, '7/10/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (3, 3, 'Nescafe - Frothy French Vanilla', 'Yearly', 30, 38, 74, '11/15/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (4, 4, 'Cookie Double Choco', 'Yearly', 41, 90, 58, '7/20/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (5, 5, 'Longos - Grilled Veg Sandwiches', 'Monthly', 100, 51, 109, '1/25/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (6, 6, 'Crackers - Graham', 'Daily', 46, 59, 28, '10/26/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (7, 7, 'Pork - Suckling Pig', 'Monthly', 63, 114, 107, '5/29/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (8, 8, 'Vaccum Bag - 14x20', 'Never', 102, 68, 39, '4/13/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (9, 9, 'Leeks - Baby, White', 'Often', 118, 79, 2, '11/16/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (10, 10, 'Bread - Corn Muffaletta', 'Never', 68, 23, 54, '11/24/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (11, 11, 'Shallots', 'Once', 70, 78, 105, '4/5/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (12, 12, 'Waffle Stix', 'Daily', 50, 70, 10, '11/16/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (13, 13, 'Nut - Pecan, Halves', 'Once', 22, 56, 82, '3/3/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (14, 14, 'Garlic Powder', 'Often', 47, 113, 45, '6/14/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (15, 15, 'Mushroom - King Eryingii', 'Never', 69, 10, 42, '2/7/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (16, 16, 'Beer - True North Strong Ale', 'Daily', 36, 59, 85, '9/9/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (17, 17, 'Mushroom - Enoki, Fresh', 'Monthly', 60, 112, 83, '9/15/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (18, 18, 'Sauce - Chili', 'Never', 118, 68, 62, '9/21/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (19, 19, 'Shrimp - Tiger 21/25', 'Yearly', 95, 15, 13, '5/30/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (20, 20, 'Chip - Potato Dill Pickle', 'Monthly', 112, 104, 122, '12/29/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (21, 21, 'Pineapple - Canned, Rings', 'Once', 74, 112, 35, '3/9/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (22, 22, 'Everfresh Products', 'Never', 101, 108, 35, '10/30/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (23, 23, 'Truffle Cups - White Paper', 'Once', 109, 79, 15, '7/20/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (24, 24, 'Truffle Shells - White Chocolate', 'Yearly', 63, 72, 50, '7/17/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (25, 25, 'Wine - White, Concha Y Toro', 'Seldom', 100, 113, 35, '7/13/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (26, 26, 'Munchies Honey Sweet Trail Mix', 'Weekly', 101, 37, 22, '12/7/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (27, 27, 'Wine - Beaujolais Villages', 'Often', 89, 120, 116, '3/4/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (28, 28, 'Milk - Chocolate 250 Ml', 'Seldom', 31, 100, 4, '9/23/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (29, 29, 'Split Peas - Yellow, Dry', 'Weekly', 12, 63, 111, '11/24/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (30, 30, 'Nut - Cashews, Whole, Raw', 'Weekly', 71, 78, 17, '4/13/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (31, 31, 'Ginger - Crystalized', 'Once', 63, 17, 118, '8/2/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (32, 32, 'Noodles - Steamed Chow Mein', 'Often', 28, 79, 90, '7/19/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (33, 33, 'Wine - Kwv Chenin Blanc South', 'Seldom', 41, 59, 83, '10/1/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (34, 34, 'Bread - Calabrese Baguette', 'Often', 72, 28, 53, '5/25/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (35, 35, 'Wine - Chablis J Moreau Et Fils', 'Daily', 73, 90, 50, '2/23/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (36, 36, 'Mountain Dew', 'Yearly', 82, 35, 25, '11/13/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (37, 37, 'Venison - Denver Leg Boneless', 'Seldom', 81, 49, 104, '9/1/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (38, 38, 'Table Cloth - 53x69 Colour', 'Once', 21, 119, 57, '7/2/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (39, 39, 'The Pop Shoppe - Root Beer', 'Never', 8, 101, 34, '9/4/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (40, 40, 'Bar - Sweet And Salty Chocolate', 'Never', 120, 35, 53, '10/11/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (41, 41, 'Lemonade - Black Cherry, 591 Ml', 'Yearly', 39, 47, 121, '11/13/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (42, 42, 'Coffee - Colombian, Portioned', 'Monthly', 21, 14, 51, '9/4/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (43, 43, 'Cake - Night And Day Choclate', 'Yearly', 107, 90, 89, '12/15/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (44, 44, 'Goat - Leg', 'Never', 82, 43, 94, '8/17/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (45, 45, 'Soap - Pine Sol Floor Cleaner', 'Once', 32, 108, 72, '9/26/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (46, 46, 'Trout - Smoked', 'Monthly', 104, 70, 102, '3/18/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (47, 47, 'Bread - French Stick', 'Monthly', 28, 91, 2, '1/31/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (48, 48, 'Cake - Miini Cheesecake Cherry', 'Seldom', 2, 123, 113, '6/19/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (49, 49, 'Sauce - Thousand Island', 'Weekly', 99, 80, 110, '6/26/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (50, 50, 'Lamb - Whole Head Off,nz', 'Once', 25, 12, 77, '6/20/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (51, 51, 'Peppercorns - Green', 'Often', 46, 11, 42, '10/10/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (52, 52, 'Wanton Wrap', 'Monthly', 93, 45, 59, '3/7/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (53, 53, 'Jameson - Irish Whiskey', 'Weekly', 27, 75, 9, '7/31/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (54, 54, 'Truffle - Whole Black Peeled', 'Weekly', 65, 82, 106, '4/1/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (55, 55, 'Yukon Jack', 'Once', 10, 72, 102, '6/19/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (56, 56, 'Juice - Apple, 1.36l', 'Once', 83, 105, 55, '6/13/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (57, 57, 'Dawn Professionl Pot And Pan', 'Weekly', 88, 16, 103, '1/21/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (58, 58, 'Cheese - Cottage Cheese', 'Yearly', 86, 123, 59, '10/16/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (59, 59, 'Soup - Campbells, Creamy', 'Weekly', 5, 92, 79, '9/21/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (60, 60, 'Green Scrubbie Pad H.duty', 'Monthly', 9, 32, 103, '11/16/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (61, 61, 'Mushroom - Porcini, Dry', 'Once', 31, 39, 24, '8/16/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (62, 62, 'Onions Granulated', 'Once', 79, 56, 51, '1/16/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (63, 63, 'Kiwi', 'Seldom', 57, 55, 114, '5/9/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (64, 64, 'Syrup - Pancake', 'Never', 15, 93, 30, '1/9/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (65, 65, 'Container - Clear 32 Oz', 'Seldom', 81, 123, 122, '11/17/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (66, 66, 'Wine - Chardonnay Mondavi', 'Seldom', 28, 109, 119, '9/17/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (67, 67, 'Syrup - Pancake', 'Seldom', 30, 62, 113, '3/6/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (68, 68, 'Bowl 12 Oz - Showcase 92012', 'Daily', 113, 56, 68, '5/12/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (69, 69, 'Table Cloth 54x54 Colour', 'Once', 1, 123, 69, '4/14/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (70, 70, 'Pepper - Red Bell', 'Weekly', 31, 5, 70, '3/20/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (71, 71, 'Foil Cont Round', 'Seldom', 41, 55, 103, '3/2/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (72, 72, 'Relish', 'Weekly', 107, 68, 18, '7/31/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (73, 73, 'Cookies - Assorted', 'Weekly', 64, 25, 28, '8/7/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (74, 74, 'Pasta - Penne, Rigate, Dry', 'Never', 85, 84, 22, '4/9/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (75, 75, 'Scallops - In Shell', 'Yearly', 4, 80, 9, '4/16/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (76, 76, 'Muffin Batt - Carrot Spice', 'Seldom', 92, 113, 81, '7/4/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (77, 77, 'Beer - Tetleys', 'Weekly', 26, 96, 103, '4/19/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (78, 78, 'Spoon - Soup, Plastic', 'Once', 76, 61, 22, '4/29/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (79, 79, 'Shrimp - Black Tiger 8 - 12', 'Yearly', 27, 113, 108, '8/7/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (80, 80, 'Bagelers - Cinn / Brown', 'Once', 66, 71, 35, '12/7/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (81, 81, 'Rolled Oats', 'Often', 122, 80, 71, '9/30/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (82, 82, 'Orange - Blood', 'Monthly', 32, 2, 92, '3/25/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (83, 83, 'Cookie Choc', 'Yearly', 63, 89, 19, '12/21/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (84, 84, 'Syrup - Kahlua Chocolate', 'Often', 88, 75, 122, '3/9/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (85, 85, 'Chips - Miss Vickies', 'Once', 99, 101, 17, '3/31/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (86, 86, 'Wine - White, Pelee Island', 'Seldom', 108, 24, 2, '7/25/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (87, 87, 'Initation Crab Meat', 'Weekly', 99, 67, 115, '2/17/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (88, 88, 'Bagelers - Cinn / Brown Sugar', 'Yearly', 116, 14, 55, '12/23/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (89, 89, 'Bread Base - Toscano', 'Once', 80, 75, 92, '11/27/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (90, 90, 'Flavouring - Rum', 'Never', 113, 30, 98, '4/17/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (91, 91, 'Turnip - Mini', 'Monthly', 105, 86, 81, '12/7/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (92, 92, 'Beef - Rib Roast, Cap On', 'Weekly', 46, 24, 26, '12/24/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (93, 93, 'Cassis', 'Often', 120, 83, 81, '11/2/2023');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (94, 94, 'Juice - Apple Cider', 'Daily', 35, 54, 27, '3/8/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (95, 95, 'Pomegranates', 'Once', 32, 38, 94, '8/16/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (96, 96, 'Bread - Hamburger Buns', 'Daily', 29, 18, 28, '9/5/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (97, 97, 'Wine - Beaujolais Villages', 'Often', 9, 54, 86, '9/14/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (98, 98, 'Lumpfish Black', 'Weekly', 17, 28, 56, '4/11/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (99, 99, 'Soup Campbells Split Pea And Ham', 'Daily', 103, 46, 17, '4/5/2024');
insert into Nutrition (Nutrition_ID, User_ID, Food_Item, Calories, Protein, Carbohydrates, Fats, Meal_Date) values (100, 100, 'Mustard - Pommery', 'Never', 99, 40, 31, '5/3/2024');
